server:
  port: 8088    #端口号
#数据库配置
spring:
  datasource:           #数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/tianjian_lock?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root

    #数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
  redis:
    host: 120.76.178.26
    port: 11007
    database: 10
    password: Tagen2020@!#%
    #password:
    #设置jedis连接池
    jedis:
      pool:
        max-active: 50
        min-idle: 20

  #服务名称
  application:
    name: Property-lock   #服务名
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
#配置eureka(注册中心)
eureka:
  client:
    service-url:
      # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
      defaultZone: http://127.0.0.1:11007/eureka
  instance:
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: true
    # 应用实例IP
    ip-address: 127.0.0.1
    # 实例ID
    instance-id: ${eureka.instance.ip-address}.${server.port}
    # 服务续约（心跳）频率，单位：秒，缺省30
    lease-renewal-interval-in-seconds: 3
    # 服务失效时间，失效的服务将被剔除。单位：秒，默认：90
    lease-expiration-duration-in-seconds: 10

#mybatis配置
#pojo包名（此项必须与 entity项目中的包保持一致）
mybatis:
  type-aliases-package: com.tianjian.Property.bean.entity
  #开启注解sql查询转驼峰式
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#通用mapper配置
#mapper:
#  not-empty: false
#  identity: mysql

#分页插件配置
pagehelper:
  #数据库方言
  helper-dialect: mysql
  #页数大小异常处理
  reasonable: false
  #支持通过mapper接口传递参数
  support-methods-arguments: true
  #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
  page-size-zero: true
  params:
    count: countSql

####日志输出
#logging:
#  # 服务器
#  pattern:
#    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
#    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'
#  file:
#    name: ${catalina.home}\logs\lock_logs.log
#  level:
#    root: info
#    org.springframework.web: DEBUG
#


